/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Array Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.ArrayType#getArrayElements <em>Array Elements</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getArrayType()
 * @model
 * @generated
 */
public interface ArrayType extends ElementType
{
  /**
   * Returns the value of the '<em><b>Array Elements</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.ArrayElement}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Array Elements</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Array Elements</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getArrayType_ArrayElements()
   * @model containment="true"
   * @generated
   */
  EList<ArrayElement> getArrayElements();

} // ArrayType
