/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Basic Type</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getBasicType()
 * @model
 * @generated
 */
public interface BasicType extends ElementType
{
} // BasicType
