/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Verb</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Verb#getVerb <em>Verb</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Verb#getQa <em>Qa</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Verb#getRules <em>Rules</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getVerb()
 * @model
 * @generated
 */
public interface Verb extends Member
{
  /**
   * Returns the value of the '<em><b>Verb</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Verb</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Verb</em>' attribute.
   * @see #setVerb(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getVerb_Verb()
   * @model
   * @generated
   */
  String getVerb();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Verb#getVerb <em>Verb</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Verb</em>' attribute.
   * @see #getVerb()
   * @generated
   */
  void setVerb(String value);

  /**
   * Returns the value of the '<em><b>Qa</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Qa</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Qa</em>' attribute.
   * @see #setQa(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getVerb_Qa()
   * @model
   * @generated
   */
  String getQa();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Verb#getQa <em>Qa</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Qa</em>' attribute.
   * @see #getQa()
   * @generated
   */
  void setQa(String value);

  /**
   * Returns the value of the '<em><b>Rules</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.Rule}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Rules</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rules</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getVerb_Rules()
   * @model containment="true"
   * @generated
   */
  EList<Rule> getRules();

} // Verb
